package cz.pzrevize.mobile;

final class InfluenceCatalog {
    private InfluenceCatalog() {}
    static final String[][] ITEMS = new String[][] {
        {"AA", "Teplota okolí", "AA1", "−60 °C až +5 °C", "Použít speciálně navržené zařízení nebo vhodnou úpravu pro daný teplotní rozsah; podle zařízení mohou být nutná doplňková opatření."},
        {"AA", "Teplota okolí", "AA2", "−40 °C až +5 °C", "Použít speciálně navržené zařízení nebo vhodnou úpravu pro daný teplotní rozsah; podle zařízení mohou být nutná doplňková opatření."},
        {"AA", "Teplota okolí", "AA3", "−25 °C až +5 °C", "Použít speciálně navržené zařízení nebo vhodnou úpravu pro daný teplotní rozsah; podle zařízení mohou být nutná doplňková opatření."},
        {"AA", "Teplota okolí", "AA4", "−5 °C až +40 °C", "Normální podmínky; v určitých případech se dovoluje přijmout zvláštní opatření podle konkrétního zařízení."},
        {"AA", "Teplota okolí", "AA5", "+5 °C až +40 °C", "Normální podmínky."},
        {"AA", "Teplota okolí", "AA6", "+5 °C až +60 °C", "Použít speciálně navržené zařízení nebo vhodnou úpravu pro daný teplotní rozsah; podle zařízení mohou být nutná doplňková opatření."},
        {"AA", "Teplota okolí", "AA7", "−25 °C až +55 °C", "Použít speciálně navržené zařízení nebo vhodnou úpravu pro daný teplotní rozsah; podle zařízení mohou být nutná doplňková opatření."},
        {"AA", "Teplota okolí", "AA8", "−50 °C až +40 °C", "Použít speciálně navržené zařízení nebo vhodnou úpravu pro daný teplotní rozsah; podle zařízení mohou být nutná doplňková opatření."},
        {"AB", "Atmosférické podmínky v okolí", "AB1", "−60 až +5 °C; RV 3–100 %", "Pro extrémně nízkou teplotu a současnou vlhkost navrhnout zvláštní opatření a zařízení vhodné pro daný rozsah."},
        {"AB", "Atmosférické podmínky v okolí", "AB2", "−40 až +5 °C; RV 10–100 %", "Pro extrémně nízkou teplotu a současnou vlhkost navrhnout zvláštní opatření a zařízení vhodné pro daný rozsah."},
        {"AB", "Atmosférické podmínky v okolí", "AB3", "−25 až +5 °C; RV 10–100 %", "Pro nízkou teplotu a současnou vysokou vlhkost navrhnout zvláštní opatření a zařízení vhodné pro daný rozsah."},
        {"AB", "Atmosférické podmínky v okolí", "AB4", "−5 až +40 °C; RV 5–95 %", "Normální podmínky pro prostory chráněné před atmosférickými vlivy bez regulace teploty a vlhkosti; ke zvýšení nízké teploty lze použít vytápění."},
        {"AB", "Atmosférické podmínky v okolí", "AB5", "+5 až +40 °C; RV 5–85 %", "Normální podmínky pro prostory chráněné před atmosférickými vlivy s regulací teploty."},
        {"AB", "Atmosférické podmínky v okolí", "AB6", "+5 až +60 °C; RV 10–100 %", "Pro extrémně vysokou teplotu a současnou vysokou vlhkost navrhnout zvláštní opatření a zařízení vhodné pro daný rozsah."},
        {"AB", "Atmosférické podmínky v okolí", "AB7", "−25 až +55 °C; RV 10–100 %", "Pro venkovní / nechráněné podmínky s velkým rozsahem teplot a vlhkosti navrhnout zvláštní opatření."},
        {"AB", "Atmosférické podmínky v okolí", "AB8", "−50 až +40 °C; RV 15–100 %", "Pro velmi náročné venkovní / nechráněné podmínky s velkým rozsahem teplot a vlhkosti navrhnout zvláštní opatření."},
        {"AC", "Nadmořská výška", "AC1", "nadmořská výška ≤ 2 000 m", "Normální podmínky."},
        {"AC", "Nadmořská výška", "AC2", "nadmořská výška > 2 000 m", "Mohou být vyžadována speciální bezpečnostní opatření, např. uplatnění korekčních součinitelů s ohledem na nadmořskou výšku; respektovat údaje výrobce."},
        {"AD", "Výskyt vody", "AD1", "výskyt vody zanedbatelný", "Zanedbatelný výskyt vody; požadované krytí IPX0. V ČR se AD1 považuje za normální."},
        {"AD", "Výskyt vody", "AD2", "svisle padající kapky", "Volně padající kapky; požadované krytí IPX1 nebo IPX2 podle podmínek působení."},
        {"AD", "Výskyt vody", "AD3", "vodní tříšť", "Vodní tříšť; požadované krytí IPX3."},
        {"AD", "Výskyt vody", "AD4", "stříkající voda", "Stříkající voda; požadované krytí IPX4."},
        {"AD", "Výskyt vody", "AD5", "tryskající voda", "Tryskající voda; požadované krytí IPX5."},
        {"AD", "Výskyt vody", "AD6", "vlny / zaplavení", "Vlny; požadované krytí IPX6."},
        {"AD", "Výskyt vody", "AD7", "mělké ponoření", "Mělké ponoření; požadované krytí IPX7 a zařízení vhodné pro předpokládané podmínky ponoření."},
        {"AD", "Výskyt vody", "AD8", "hluboké ponoření", "Hluboké ponoření; požadované krytí IPX8, podmínky hloubky / doby podle určení zařízení."},
        {"AE", "Výskyt cizích pevných těles", "AE1", "výskyt cizích pevných těles zanedbatelný", "Zanedbatelný výskyt cizích pevných těles; IP0X. V ČR se AE1 považuje za normální."},
        {"AE", "Výskyt cizích pevných těles", "AE2", "malé předměty (2,5 mm)", "Malé předměty (2,5 mm); požadované krytí IP3X."},
        {"AE", "Výskyt cizích pevných těles", "AE3", "velmi malé předměty (1 mm)", "Velmi malé předměty (1 mm); požadované krytí IP4X."},
        {"AE", "Výskyt cizích pevných těles", "AE4", "lehká prašnost", "Lehká prašnost; IP5X, pokud pronikání prachu není pro funkci škodlivé."},
        {"AE", "Výskyt cizích pevných těles", "AE5", "střední prašnost", "Střední prašnost; IP6X."},
        {"AE", "Výskyt cizích pevných těles", "AE6", "silná prašnost", "Silná prašnost; IP6X a zařízení vhodné pro silnou prašnost."},
        {"AF", "Výskyt korozivních nebo znečišťujících látek", "AF1", "korozivní / znečišťující látky – zanedbatelný výskyt", "Zanedbatelný výskyt korozivních nebo znečišťujících látek; normální podmínky."},
        {"AF", "Výskyt korozivních nebo znečišťujících látek", "AF2", "atmosférický výskyt", "Atmosférický výskyt korozivních nebo znečišťujících látek; volit zařízení a materiály podle povahy látek a požadované korozní odolnosti."},
        {"AF", "Výskyt korozivních nebo znečišťujících látek", "AF3", "občasný nebo příležitostný výskyt", "Občasný nebo příležitostný výskyt chemických látek; ochranu proti korozi volit podle specifikace zařízení a konkrétních látek."},
        {"AF", "Výskyt korozivních nebo znečišťujících látek", "AF4", "trvalý výskyt", "Trvalý výskyt korozivních nebo znečišťujících látek; použít zařízení speciálně navržené podle povahy působících látek."},
        {"AG", "Mechanické namáhání – ráz", "AG1", "ráz – mírný", "Nízká závažnost rázů; normální podmínky, např. domácí a podobná zařízení."},
        {"AG", "Mechanické namáhání – ráz", "AG2", "ráz – střední", "Střední závažnost rázů; použít standardní průmyslové zařízení, je-li potřebné, se zesílenou ochranou."},
        {"AG", "Mechanické namáhání – ráz", "AG3", "ráz – silný", "Silná závažnost rázů; použít zesílenou ochranu."},
        {"AH", "Vibrace", "AH1", "vibrace – mírné", "Nízká závažnost vibrací; normální podmínky."},
        {"AH", "Vibrace", "AH2", "vibrace – střední", "Střední závažnost vibrací; pro obvyklé průmyslové podmínky použít speciálně navržené zařízení nebo speciální úpravu."},
        {"AH", "Vibrace", "AH3", "vibrace – silné", "Silná závažnost vibrací; pro náročné průmyslové podmínky použít speciálně navržené zařízení nebo speciální úpravu."},
        {"AK", "Výskyt rostlinstva nebo plísní", "AK1", "rostlinstvo / plísně – bez nebezpečí", "Bez vážného nebezpečí způsobeného růstem rostlin nebo plísní; normální podmínky."},
        {"AK", "Výskyt rostlinstva nebo plísní", "AK2", "rostlinstvo / plísně – nebezpečný výskyt", "Nebezpečný výskyt rostlin / plísní; ochrana může zahrnovat zvýšenou ochranu proti pronikání cizích těles, zvláštní materiály nebo nátěry krytů a opatření vylučující přítomnost rostlin v prostoru."},
        {"AL", "Výskyt živočichů", "AL1", "živočichové – bez nebezpečí", "Bez škodlivého nebezpečí ze strany živočichů; normální podmínky."},
        {"AL", "Výskyt živočichů", "AL2", "živočichové – nebezpečný výskyt", "Nebezpečný výskyt živočichů; ochrana může zahrnovat vhodný stupeň ochrany proti cizím tělesům, mechanickou odolnost, vyloučení živočichů z prostoru a zvláštní zařízení nebo ochranné nátěry."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-1-1", "harmonické / meziharmonické – kontrolovaná úroveň", "Zabezpečit, aby se kontrolovaná úroveň harmonických / meziharmonických nezhoršila."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-1-2", "harmonické / meziharmonické – normální úroveň", "Normální úroveň; bez zvláštních opatření nad rámec běžného návrhu."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-1-3", "harmonické / meziharmonické – vysoká úroveň", "V návrhu instalace použít zvláštní opatření, např. filtry."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-2-1", "signální napětí – kontrolovaná úroveň", "Kontrolovaná úroveň signálního napětí; lze použít blokovací obvody."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-2-2", "signální napětí – střední úroveň", "Střední úroveň signálního napětí; bez dodatečných požadavků."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-2-3", "signální napětí – vysoká úroveň", "Vysoká úroveň signálního napětí; použít zvláštní opatření."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-3-1", "změny amplitudy napětí – kontrolovaná úroveň", "Kontrolovaná úroveň změn amplitudy napětí; např. kontrola pomocí UPS."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-3-2", "změny amplitudy napětí – normální úroveň", "Normální úroveň změn amplitudy napětí; postupovat podle příslušného odkazu normy."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-4", "neustálené napětí", "Neustálené napětí; postupovat podle EN 61000-2-2."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-5", "změny kmitočtu", "Změny kmitočtu; ±1 Hz v souladu s EN 61000-2-2."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-6", "indukované napětí nízkého kmitočtu", "Indukované napětí nízkého kmitočtu; postupovat podle HD 60364-4-444 a požadovat vysokou odolnost signalizačních a řídicích systémů."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-7", "stejnosměrný proud v obvodech střídavého proudu", "Stejnosměrný proud v sítích střídavého proudu; omezit jeho přítomnost v úrovni a čase ve spotřebičích nebo v jejich blízkosti."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-8-1", "vyzařovaná magnetická pole – střední úroveň", "Střední úroveň vyzařovaného magnetického pole; normální podmínky."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-8-2", "vyzařovaná magnetická pole – vysoká úroveň", "Vysoká úroveň vyzařovaného magnetického pole; použít vhodná ochranná opatření, např. clonu a/nebo oddělení."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-9-1", "elektrická pole – zanedbatelná úroveň", "Zanedbatelná úroveň elektrického pole; normální podmínky."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-9-2", "elektrická pole – střední úroveň", "Střední úroveň elektrického pole; posoudit podle IEC/TR 61000-2-5."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-9-3", "elektrická pole – vysoká úroveň", "Vysoká úroveň elektrického pole; posoudit podle IEC/TR 61000-2-5."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-9-4", "elektrická pole – velmi vysoká úroveň", "Velmi vysoká úroveň elektrického pole; posoudit podle IEC/TR 61000-2-5."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-21", "indukovaná oscilující napětí nebo proudy", "Indukovaná oscilační napětí nebo proudy; bez třídění, normální."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-22-1", "rychlé přechodné jevy vedením – zanedbatelná úroveň", "Zanedbatelná úroveň rychlých přechodných jevů; ochranná opatření jsou nezbytná."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-22-2", "rychlé přechodné jevy vedením – střední úroveň", "Střední úroveň rychlých přechodných jevů; ochranná opatření jsou nezbytná."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-22-3", "rychlé přechodné jevy vedením – vysoká úroveň", "Vysoká úroveň rychlých přechodných jevů; normální zařízení."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-22-4", "rychlé přechodné jevy vedením – velmi vysoká úroveň", "Velmi vysoká úroveň rychlých přechodných jevů; použít vysoce odolné zařízení."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-23-1", "přechodná přepětí vedením – kontrolovaná úroveň", "Odolnost zařízení proti přechodným přepětím a ochranné prostředky proti přepětí zvolit podle jmenovitého napětí a kategorie odolnosti proti přepětí."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-23-2", "přechodná přepětí vedením – střední úroveň", "Odolnost zařízení proti přechodným přepětím a ochranné prostředky proti přepětí zvolit podle jmenovitého napětí a kategorie odolnosti proti přepětí."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-23-3", "přechodná přepětí vedením – vysoká úroveň", "Odolnost zařízení proti přechodným přepětím a ochranné prostředky proti přepětí zvolit podle jmenovitého napětí a kategorie odolnosti proti přepětí."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-24-1", "oscilační přechodové jevy vedením – střední úroveň", "Střední úroveň oscilačních přechodových jevů; postupovat podle EN 61000-4-12."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-24-2", "oscilační přechodové jevy vedením – vysoká úroveň", "Vysoká úroveň oscilačních přechodových jevů; postupovat podle EN 60255-22-1."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-25-1", "vysokofrekvenční vyzařované jevy – zanedbatelná úroveň", "Zanedbatelná úroveň vyzařovaných vysokofrekvenčních jevů; úroveň odolnosti 1."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-25-2", "vysokofrekvenční vyzařované jevy – střední úroveň", "Střední úroveň vyzařovaných vysokofrekvenčních jevů; normální zařízení, úroveň odolnosti 2."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-25-3", "vysokofrekvenční vyzařované jevy – vysoká úroveň", "Vysoká úroveň vyzařovaných vysokofrekvenčních jevů; požadována zvýšená odolnost, úroveň 3."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-31-1", "elektrostatické výboje – nízká úroveň", "Nízká úroveň elektrostatických výbojů; normální zařízení, úroveň 1."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-31-2", "elektrostatické výboje – střední úroveň", "Střední úroveň elektrostatických výbojů; normální zařízení, úroveň 2."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-31-3", "elektrostatické výboje – vysoká úroveň", "Vysoká úroveň elektrostatických výbojů; normální zařízení, úroveň 3."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-31-4", "elektrostatické výboje – velmi vysoká úroveň", "Velmi vysoká úroveň elektrostatických výbojů; požadováno vyztužení / zvýšená odolnost, úroveň 4."},
        {"AM", "Elektromagnetická, elektrostatická nebo ionizující působení", "AM-41-1", "ionizace – bez třídění", "Ionizace bez klasifikace; speciální ochrana může zahrnovat vzdálenost od zdroje a vložení clon / krytů ze speciálních materiálů."},
        {"AN", "Intenzita slunečního záření", "AN1", "sluneční záření – nízké", "Nízká intenzita slunečního záření (≤ 500 W/m²); normální podmínky."},
        {"AN", "Intenzita slunečního záření", "AN2", "sluneční záření – střední", "Střední intenzita slunečního záření; musí být provedena vhodná opatření."},
        {"AN", "Intenzita slunečního záření", "AN3", "sluneční záření – vysoké", "Vysoká intenzita slunečního záření; vhodná opatření mohou zahrnovat materiály odolné proti UV, speciální barevný nátěr nebo vložení clon."},
        {"AP", "Seizmické účinky", "AP1", "seizmické účinky – zanedbatelné", "Zanedbatelné seizmické účinky (zrychlení ≤ 30 Gal); normální podmínky."},
        {"AP", "Seizmické účinky", "AP2", "seizmické účinky – nízké ohrožení", "Nízká úroveň seizmických účinků (30 < zrychlení ≤ 300 Gal); konkrétní opatření se zvažují podle objektu a zařízení."},
        {"AP", "Seizmické účinky", "AP3", "seizmické účinky – střední ohrožení", "Střední úroveň seizmických účinků (300 < zrychlení ≤ 600 Gal); konkrétní opatření se zvažují podle objektu a zařízení."},
        {"AP", "Seizmické účinky", "AP4", "seizmické účinky – vysoké ohrožení", "Vysoká úroveň seizmických účinků (> 600 Gal); konkrétní opatření se zvažují podle objektu a zařízení."},
        {"AQ", "Blesková úroveň", "AQ1", "úder blesku – zanedbatelný", "Zanedbatelná blesková úroveň / hustota; normální podle posouzení rizika."},
        {"AQ", "Blesková úroveň", "AQ2", "nepřímé ohrožení", "Nepřímé ohrožení; v tabulce ZA.1 uvedeno jako normální, podle hodnot nebo výsledku posouzení rizika."},
        {"AQ", "Blesková úroveň", "AQ3", "přímé ohrožení", "Přímé ohrožení; nebezpečí zasažení zařízení. Je-li ochrana před bleskem důležitá, řešit ji podle souboru EN 62305; části instalace umístěné vně budov posoudit zvlášť."},
        {"AR", "Pohyb vzduchu", "AR1", "pohyb vzduchu – pomalý", "Pomalý pohyb vzduchu (rychlost < 1 m/s); normální podmínky."},
        {"AR", "Pohyb vzduchu", "AR2", "pohyb vzduchu – střední", "Střední pohyb vzduchu (1 až 5 m/s); musí být provedena vhodná opatření."},
        {"AR", "Pohyb vzduchu", "AR3", "pohyb vzduchu – silný", "Silný pohyb vzduchu (5 až 10 m/s); musí být provedena vhodná opatření."},
        {"AS", "Vítr", "AS1", "vítr – malý", "Malý vítr (rychlost ≤ 20 m/s); normální podmínky."},
        {"AS", "Vítr", "AS2", "vítr – střední", "Střední vítr (20 až 30 m/s); musí být provedena vhodná opatření."},
        {"AS", "Vítr", "AS3", "vítr – silný", "Silný vítr (30 až 50 m/s); musí být provedena vhodná opatření."},
        {"BA", "Schopnost osob", "BA1", "schopnost osob – běžná", "Laici / nepoučené osoby; normální podmínky."},
        {"BA", "Schopnost osob", "BA2", "děti", "Místa určená pro přítomnost dětí: použít zařízení se stupněm ochrany vyšším než IP2XC a znepřístupnit zařízení s povrchovou teplotou nad 60 °C."},
        {"BA", "Schopnost osob", "BA3", "osoby se sníženými schopnostmi", "Osoby s omezenými fyzickými nebo duševními schopnostmi; opatření určit podle povahy postižení."},
        {"BA", "Schopnost osob", "BA4", "poučené osoby", "Osoby odpovídajícím způsobem poučené nebo pracující pod dohledem osoby znalé tak, aby se mohly vyhnout nebezpečí úrazu elektrickým proudem; typicky elektrotechnické pracovní prostory."},
        {"BA", "Schopnost osob", "BA5", "odborníci / osoby znalé", "Osoby znalé: zařízení nechráněná proti přímému dotyku lze připustit jen v místech přístupných řádně označeným a oprávněným osobám s technickými znalostmi nebo zkušenostmi umožňujícími vyhnout se nebezpečí."},
        {"BC", "Kontakt osob s potenciálem země", "BC1", "kontakt osob s potenciálem země – žádný", "Žádný kontakt s potenciálem země; osoby jsou v nevodivém prostředí."},
        {"BC", "Kontakt osob s potenciálem země", "BC2", "kontakt výjimečný", "Příležitostný kontakt; osoby se obvykle nedotýkají cizích vodivých částí ani nestojí na vodivém podkladu. V ČR je BC2 považován za normální."},
        {"BC", "Kontakt osob s potenciálem země", "BC3", "kontakt částečný", "Častý kontakt; osoby se obvykle dotýkají cizích vodivých částí nebo stojí na vodivém podkladu. Volbu ochrany přizpůsobit konkrétním podmínkám."},
        {"BC", "Kontakt osob s potenciálem země", "BC4", "kontakt trvalý", "Trvalý kontakt; osoby jsou ponořené ve vodě nebo dlouhodobě v kontaktu s kovovým prostředím a možnost přerušení kontaktu je omezená. Konkrétní opatření se zvažují individuálně."},
        {"BD", "Podmínky úniku v případě nebezpečí", "BD1", "malá hustota osob / snadný únik", "Malý počet osob a snadné podmínky pro evakuaci; normální podmínky."},
        {"BD", "Podmínky úniku v případě nebezpečí", "BD2", "malá hustota osob / obtížný únik", "Malý počet osob, obtížné podmínky pro evakuaci (např. vícepodlažní budovy); konkrétní opatření určit podle požárně bezpečnostního řešení a souvisejících předpisů."},
        {"BD", "Podmínky úniku v případě nebezpečí", "BD3", "velká hustota osob / snadný únik", "Vysoký počet osob, snadné podmínky pro evakuaci (např. veřejně přístupná místa); konkrétní opatření určit podle požárně bezpečnostního řešení a souvisejících předpisů."},
        {"BD", "Podmínky úniku v případě nebezpečí", "BD4", "velká hustota osob / obtížný únik", "Vysoký počet osob, obtížné podmínky pro evakuaci (např. vícepodlažní veřejně přístupné budovy); konkrétní opatření určit podle požárně bezpečnostního řešení a souvisejících předpisů."},
        {"BE", "Povaha zpracovávaných nebo skladovaných materiálů", "BE1", "bez významného nebezpečí", "Bez významného nebezpečí; normální podmínky."},
        {"BE", "Povaha zpracovávaných nebo skladovaných materiálů", "BE2", "nebezpečí požáru", "Nebezpečí požáru při výrobě, zpracování nebo skladování hořlavých materiálů včetně prachu; zařízení musí omezovat šíření plamene a úpravami zabránit tomu, aby oteplení nebo jiskra způsobily požár."},
        {"BE", "Povaha zpracovávaných nebo skladovaných materiálů", "BE3", "nebezpečí výbuchu", "Nebezpečí výbuchu; požadavky na elektrická zařízení určená pro použití ve výbušné atmosféře řešit podle souboru EN 60079 a podle konkrétní klasifikace prostoru."},
        {"BE", "Povaha zpracovávaných nebo skladovaných materiálů", "BE4", "nebezpečí kontaminace", "Nebezpečí kontaminace nechráněných potravin, léčiv nebo obdobných produktů; podle provozu zabránit kontaminaci např. úlomky z rozbitých světelných zdrojů a škodlivým zářením."},
        {"CA", "Stavební materiál", "CA1", "stavební materiál – nehořlavý", "Nehořlavé stavební materiály; normální podmínky."},
        {"CA", "Stavební materiál", "CA2", "stavební materiál – hořlavý", "Hořlavé stavební materiály / dřevostavby; konkrétní opatření se zvažují podle ochrany před tepelnými účinky a souvisejících pravidel."},
        {"CB", "Provedení / konstrukce budovy", "CB1", "konstrukce budovy – zanedbatelné nebezpečí", "Zanedbatelné nebezpečí konstrukce budovy; normální podmínky."},
        {"CB", "Provedení / konstrukce budovy", "CB2", "šíření požáru", "Nebezpečí šíření požáru; použít zařízení z materiálu zpomalujícího šíření požáru a zachovat / doplnit protipožární bariéry."},
        {"CB", "Provedení / konstrukce budovy", "CB3", "posun konstrukce", "Posun konstrukce; zohlednit pohyb konstrukce a použít kontrakční nebo expanzní spoje v elektrickém vedení podle potřeby."},
        {"CB", "Provedení / konstrukce budovy", "CB4", "poddajná nebo nestabilní konstrukce", "Poddajná nebo nestabilní konstrukce; instalace musí být konstrukčně samonosná a podle potřeby použít ohebné vedení."},
    };
}
